name: Run Tests

on:
  push:
    branches:
      - master  # Change to your default branch (e.g., main)
  pull_request:
    branches:
      - master  # Change to your default branch (e.g., main)

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner if needed

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'  # Specify the distribution to use (e.g., adopt, zulu, temurin)

      - name: Build with Maven
        run: mvn clean install  # Use this if you're using Maven as a build tool

      - name: Run tests
        run: mvn test  # Use this if you want to run tests