name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Install Google Chrome
        run: |
          echo "Installing Google Chrome..."
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Get Chrome version
        id: get_chrome_version
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          echo "CHROME_VERSION=${CHROME_VERSION}" >> $GITHUB_ENV
          MAJOR_CHROME_VERSION=$(echo ${CHROME_VERSION} | cut -d '.' -f 1-2)
          echo "MAJOR_CHROME_VERSION=${MAJOR_CHROME_VERSION}" >> $GITHUB_ENV

      - name: Download ChromeDriver
        run: |
          echo "Requesting ChromeDriver for Chrome version ${MAJOR_CHROME_VERSION}"
          CHROME_DRIVER_VERSION=$(curl -sSL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${MAJOR_CHROME_VERSION}" | tr -d '\n')
          echo "CHROME_DRIVER_VERSION=${CHROME_DRIVER_VERSION}" >> $GITHUB_ENV
          echo "Downloading ChromeDriver version ${CHROME_DRIVER_VERSION}"
          wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/  # Move to a location in PATH
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Check Versions
        run: |
          echo "Chrome Version: $CHROME_VERSION"
          echo "ChromeDriver Version: $CHROME_DRIVER_VERSION"

      - name: Run Tests
        run: |
          # Replace with your testing command, e.g., for Maven or Gradle
          mvn test  # or ./gradlew test