name: Selenium Tests

on:
  push:
  pull_request:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - name: Install Specific Version of Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O google-chrome.deb
          sudo dpkg -i google-chrome.deb || sudo apt-get -f install -y

      - name: Set up Chrome environment
        id: chrome_setup
        run: |
          export CHROME_BIN="/usr/bin/google-chrome"
          export CHROMEWEBDRIVER="${GITHUB_WORKSPACE}/chrome_driver"
          CHROME_VERSION="114.0.5735.90"
          CHROME_DRIVER_VERSION="114.0.5735.90"
          mkdir -p "$CHROMEWEBDRIVER"
          wget "https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip -d "$CHROMEWEBDRIVER"
          chmod +x "$CHROMEWEBDRIVER/chromedriver"

      - name: Verify Chrome and ChromeDriver versions
        run: |
          "$CHROME_BIN" --version
          "$CHROMEWEBDRIVER/chromedriver" --version

      - name: Run Tests
        run: mvn test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/*.xml