name: Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - name: Install Chrome
        run: |
          # Attempt to download and install the latest Chrome version
          echo "Installing Chrome..."
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O google-chrome.deb
          sudo dpkg -i google-chrome.deb || sudo apt-get -f install -y
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          echo "Installed Chrome version: ${CHROME_VERSION}"

      - name: Get ChromeDriver version
        id: get_chromedriver
        run: |
          MAJOR_CHROME_VERSION=$(echo ${CHROME_VERSION} | cut -d '.' -f 1-2)
          echo "Requesting ChromeDriver for Chrome version ${MAJOR_CHROME_VERSION}"

          # Try to get the ChromeDriver version corresponding to the major Chrome version
          CHROME_DRIVER_VERSION=$(curl -sSL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${MAJOR_CHROME_VERSION}" || echo "")
          
          # Fallback to the latest ChromeDriver if the specific version fails
          if [ -z "$CHROME_DRIVER_VERSION" ]; then
            echo "Failed to retrieve ChromeDriver version for major version ${MAJOR_CHROME_VERSION}. Trying latest version..."
            CHROME_DRIVER_VERSION=$(curl -sSL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE" || echo "")
          fi

          # Check if ChromeDriver version retrieval was successful
          if [ -z "$CHROME_DRIVER_VERSION" ]; then
            echo "Failed to retrieve ChromeDriver version. Exiting."
            exit 1
          fi

          echo "CHROME_DRIVER_VERSION=${CHROME_DRIVER_VERSION}" >> $GITHUB_ENV
          echo "Downloading ChromeDriver version ${CHROME_DRIVER_VERSION}"
          wget "https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Tests
        run: mvn test